version: '3'

services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        env_file:
            - .env
        volumes:
            - mongodb-volume:/data/db
        ports:
            - "27017:27017"

    mongo-seed:
        build: '.'
        env_file:
            - .env
        links:
            - mongodb
        depends_on:
            - mongodb
    
    # api:
    #     build: '.'
    #     container_name: microservice-api
    #     ports:
    #         - "8080:8080"
    #     depends_on:
    #         - mongodb
    #         - mongo-seed
    #     volumes:
    #         - mongodb-volume:/data/db

volumes:
    mongodb-volume:


