# Microservice

This application was generated using http://start.vertx.io

== Descryption
A microservice that, using the REST API, made it possible to register, log in, log out, download lists of your items, attached to the item.

==== Requirements:

* Microservice based on the Vert.x library (https://vertx.io/)
* MongoDB database
* JWT authorithation (https://vertx.io/docs/vertx-auth-jwt/java/)
* Unit tests

=== Technology:
    * Java
    * Vert.x library: 4.3.7
    * MongoDB
    * JWT Auth
    
===== Tests:
    * JUnit: 5
    * Mockito: 2.19.0


==== The User object consists of:
```  
  *  id: UUID
  *  login: string
  *  password: encrypted string
```

==== The Item object consists of:
``` 
  *  id: UUID
  *  owner: UUID (user id)
  *  name: sting
```  
==== Endpoints:
* /api/login
    - `POST` - unauthorized login endpoint for users
* /api/register 
   - `POST` - unauthorized registration endpoint for users
* /api/items/:id
    - `GET` - an authorized endpoint for retrieving a list of user items
* /api/items/:id
    - `POST` - an authorized endpoint to create an item for the user
  
==== Example requests:

```
  POST localhost:8080/api/login
        Content-Type: application/json
    {
      "login": "user@domain.com",
      "password": "SomePassword1"
    }
```

```
{
    "token": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXJAZG9tYWluLmNvbSIsIl9pZCI6IjYyMTBiMWEzLTI0OTktNDQ2ZC1hNjg3LWNjZTAxMGE0OTg2NCIsImlhdCI6MTY3NTA3MjE5NywiZXhwIjoxNjc1MDc1Nzk3fQ.5EF_ZK6zin9dDUCCN6FCAmGkffwrLdfAdIaRuNleBas"
}
```

```
  POST localhost:8080/api/register
        Content-Type: application/json
    {
      "login": "user3@domain.com",
      "password": "SomePassword1"
    }
```

```
  GET localhost:8080/api/items/6210b1a3-2499-446d-a687-cce010a49864
        Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6InVzZXJAZG9tYWluLmNvbSIsIl9pZCI6IjYyMTBiMWEzLTI0OTktNDQ2ZC1hNjg3LWNjZTAxMGE0OTg2NCIsImlhdCI6MTY3NTA3MTAwOSwiZXhwIjoxNjc1MDc0NjA5fQ.Sri_STBZQM5h_PuEZGQs3cbvFABTWf4_5qaw-94iJPk
```

```
    {
        "_id": "6219b1a3-2499-546d-a687-cca010a49894",
        "owner": "6210b1a3-2499-446d-a687-cce010a49864",
        "name": "My item"
    }
```

== Running the application locally
  
Start MongoDB with docker-compose
```
docker-compose up  --build -d
```
To launch your tests:
```
./mvnw clean test
```

To package your application:
```
./mvnw clean package
```

To run your application:
```
java -jar target/mikroserwis-1.0.0-SNAPSHOT-fat.jar
```

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


